#!/bin/sh
set -e

# git-clean -x -d && ./xen-setup && make prefix=/usr CMDLINE_CFLAGS='-O0 -g' -j4 && make install DESTDIR=`pwd`/dist/ prefix=/usr && rsync -a --stats --delete . thule:shadow/qemu-iwj.git/ && rsync -a --stats dist/. root@thule:/

rm -f $target/Makefile
rm -f $target/config.mak
rm -f config-host.mak

./configure --disable-curses "$@"

target=i386-dm

case "$XEN_ROOT_PARENT" in
'')	;;
/*)	echo "XEN_ROOT=$XEN_ROOT_PARENT" 		>>config-host.mak ;;
*)	echo "XEN_ROOT=`pwd`/$XEN_ROOT_PARENT/.."	>>config-host.mak ;;
esac

ln -sf ../Makefile.target $target/Makefile
ln -sf ../xen-config.mak $target/config.mak
cat xen-config-host.mak >>config-host.mak

sed -e 's,qemu,xen/qemu,' config-host.h >config-host.h.new
echo '#include "xen-config-host.h"' >>config-host.h.new
mv config-host.h.new config-host.h
